apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace | default "oneidp" }}
  name: {{ .Release.Name }}-app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-app
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-app
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Release.Name }}-app
        ports:
          - containerPort: {{ .Values.service.port }}
        resources:
          requests:
            cpu: "50m"
            memory: "80Mi"
          limits:
            cpu: "80m"
            memory: "120Mi"
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: oneidp-secrets
              key: {{ $key | upper }}
              optional: false
        {{- end }}
