apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace | default "oneidp" }}
  name: {{ .Release.Name }}-ingress
  annotations:
    cert-manager.io/cluster-issuer: cloudflare-prod
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: oneidp.ch
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-svc
              port:
                number: {{ .Values.service.port }}
  tls:
  - hosts:
    - oneidp.ch
    secretName: oneidp-ch-tls
