apiVersion: v1
kind: Secret
metadata:
  name: oneidp-secrets
  namespace: {{ .Values.namespace | default "oneidp" }}
stringData:
  URL: {{ .Values.env.URL | quote }}
  DATABASE_URI: {{ .Values.env.DATABASE_URI | quote }}
  API_PORT: {{ .Values.env.API_PORT | quote }}
  JWT_PUBLIC_KEY: {{ .Values.env.JWT_PUBLIC_KEY | quote }}
  JWT_PRIVATE_KEY: {{ .Values.env.JWT_PRIVATE_KEY | quote }}
  MJ_APIKEY_PUBLIC: {{ .Values.env.MJ_APIKEY_PUBLIC | quote }}
  MJ_APIKEY_PRIVATE: {{ .Values.env.MJ_APIKEY_PRIVATE | quote }}
  MJ_SENDER_EMAIL: {{ .Values.env.MJ_SENDER_EMAIL | quote }}
  DC_MONITORING_WEBHOOK_URL: {{ .Values.env.DC_MONITORING_WEBHOOK_URL | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.env.GOOGLE_CLIENT_ID | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.env.GOOGLE_CLIENT_SECRET | quote }}
  GITHUB_CLIENT_ID: {{ .Values.env.GITHUB_CLIENT_ID | quote }}
  GITHUB_CLIENT_SECRET: {{ .Values.env.GITHUB_CLIENT_SECRET | quote }}
type: Opaque
