apiVersion: v1
kind: Secret
metadata:
  name: loginapp-secrets
  namespace: loginapp
stringData:
  URL: ""
  MONGODB_URI: "mongodb://root:password@loginapp-mongodb-svc.loginapp.svc:27017/"
  MONGO_INITDB_ROOT_USERNAME: ""
  MONGO_INITDB_ROOT_PASSWORD: ""
  REDIS_URI: "redis://default:"
  API_PORT: ""
  JWT_PUBLI_KEY: ""
  JWT_PRIVATE_KEY: ""
  MJ_APIKEY_PUBLIC: ""
  MJ_APIKEY_PRIVATE: ""
  MJ_SENDER_EMAIL: ""
  DC_MONITORING_WEBHOOK_URL: ""
  GOOGLE_CLIENT_ID: ""
  GOOGLE_CLIENT_SECRET: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""
type: Opaque