import { Suspense, lazy, useState } from 'react';
import { Link } from 'react-router-dom';
import { Brand } from '@/components/Brand';
import { Button, IconButton } from '@/components/ui/Button';
import {
  IconApps,
  IconCheck,
  IconClose,
  IconDevice,
  IconExternal,
  IconGitHub,
  IconGrid,
  IconKey,
  IconMail,
  IconMenu,
  IconRoles,
  IconSettings,
  IconShield,
} from '@/components/ui/Icons';
import { useDecorativeEffects } from '@/hooks/use-media';
import { useSession } from '@/session/SessionProvider';
import { cn } from '@/lib/cn';
import SpotlightCard from '@/components/reactbits/SpotlightCard';

const Aurora = lazy(() => import('@/components/reactbits/Aurora'));
const AnimatedEyebrow = lazy(() =>
  import('@/components/HeroFlourish').then((m) => ({ default: m.AnimatedEyebrow })),
);
const AnimatedHeadline = lazy(() =>
  import('@/components/HeroFlourish').then((m) => ({ default: m.AnimatedHeadline })),
);

const REPO_URL = 'https://github.com/Pablo-Wynistorf/oneidp';
const CLIENT_DEMOS_URL = 'https://github.com/Pablo-Wynistorf/oneidp-client-demo';

/** Short claims that sit under the hero CTAs. */
const HERO_CHIPS = ['MIT licensed', 'Self-hosted', 'Passkeys and MFA', 'No seat limits'];

const FEATURES = [
  {
    icon: IconShield,
    title: 'OpenID Connect, done properly',
    body: 'Discovery, authorization code flow with PKCE, refresh tokens, introspection and revocation. Tokens signed RS256 and published over JWKS.',
  },
  {
    icon: IconKey,
    title: 'Passkeys and TOTP',
    body: 'Sign in with Face ID, Touch ID or a hardware key through WebAuthn, backed up by time-based one-time codes.',
  },
  {
    icon: IconGitHub,
    title: 'Google and GitHub sign-in',
    body: 'Let people bring an account they already have, or switch social login off entirely for your instance.',
  },
  {
    icon: IconApps,
    title: 'Your own app registry',
    body: 'Register confidential and public clients, manage redirect URIs and roll secrets from the UI. No config files, no restarts.',
  },
  {
    icon: IconRoles,
    title: 'Per-application roles',
    body: 'Model authorization once and ship role claims straight into the tokens each of your applications receives.',
  },
  {
    icon: IconGrid,
    title: 'Admin console',
    body: 'Instance metrics, user search, verify and ban, plus a trail of every administrative action taken.',
  },
  {
    icon: IconDevice,
    title: 'Sessions you can see',
    body: 'Sliding 14-day sessions with device and IP context, revocable one device at a time or everywhere at once.',
  },
  {
    icon: IconMail,
    title: 'Invitations and domain rules',
    body: 'Keep signup closed and invite by email, or open it to an allow-list of the email domains you own.',
  },
  {
    icon: IconSettings,
    title: 'Switches, not redeploys',
    body: 'Registration, password reset, social login, app creation, default roles and maintenance mode are runtime settings.',
  },
];

/** Security posture, stated plainly rather than as a marketing badge. */
const SECURITY_POINTS = [
  'Rate limits on every authentication endpoint',
  'Passwords hashed with bcrypt, never logged',
  'A consent screen users can revoke afterwards',
  'Admin access comes from config, not from data',
  'Short-lived tokens with a rotating signing key',
  'Health endpoints and webhook alerting included',
];

const AWS_STACK = [
  'CloudFront in front of an API Gateway HTTP API',
  'The Express app on a single Lambda function',
  'The SPA served from S3 on that same domain',
  'RS256 signing keys generated by Terraform, never committed',
  'Your own MongoDB and Redis (Atlas and Redis Cloud work as they come)',
  'A custom domain through ACM, or start on the CloudFront one',
];

const TERMINAL_LINES = [
  { kind: 'comment', text: '# your AWS account, one apply' },
  { kind: 'cmd', text: 'git clone https://github.com/Pablo-Wynistorf/oneidp' },
  { kind: 'cmd', text: 'cd oneidp/terraform' },
  { kind: 'blank', text: '' },
  { kind: 'cmd', text: 'cp terraform.tfvars.example terraform.tfvars' },
  { kind: 'cmd', text: 'terraform init && terraform apply' },
  { kind: 'blank', text: '' },
  { kind: 'out', text: 'Apply complete! Resources: 24 added.' },
  { kind: 'out', text: 'app_url = "https://login.example.com"' },
];

const TERMINAL_TONE = {
  comment: 'text-ink-faint',
  cmd: 'text-ink',
  out: 'text-positive',
  blank: '',
};

const DISCOVERY_FIELDS = [
  ['issuer', '"https://login.example.com"'],
  ['authorization_endpoint', '".../api/oauth/authorize"'],
  ['token_endpoint', '".../api/oauth/token"'],
  ['userinfo_endpoint', '".../api/oauth/userinfo"'],
  ['jwks_uri', '".../.well-known/jwks.json"'],
  ['code_challenge_methods_supported', '["S256"]'],
  ['claims_supported', '["sub", "email", "roles", ...]'],
];

const STEPS = [
  {
    title: 'Deploy it',
    body: 'Terraform stands up the whole stack in a region you pick, or run the container image on Kubernetes.',
  },
  {
    title: 'Register your app',
    body: 'Create a client, set its redirect URIs, define the roles it cares about and hand the roles to your users.',
  },
  {
    title: 'Point your client at it',
    body: 'Any OIDC library reads the discovery document and takes it from there. Nothing bespoke to implement.',
  },
];

const NAV_LINKS = [
  { href: '#features', label: 'Features' },
  { href: '#self-host', label: 'Self-host' },
  { href: '#open-source', label: 'Open source' },
];

const LEGAL_LINKS = [
  { to: '/privacy-policy', label: 'Privacy' },
  { to: '/imprint', label: 'Imprint' },
];

// GradientText ships with `cursor-pointer` baked in; this text is not
// interactive, so the pointer is forced back off.
const EYEBROW_CLASS = 'mb-6 text-xs font-medium tracking-[0.16em] uppercase cursor-default!';

const HERO_EYEBROW = 'Open source identity provider';

/** Static stand-in for the animated gradient eyebrow. */
function Eyebrow() {
  return (
    <p
      className={`${EYEBROW_CLASS} bg-gradient-to-r from-accent to-cyan bg-clip-text text-transparent`}
    >
      {HERO_EYEBROW}
    </p>
  );
}

function SectionHeading({ eyebrow, title, children, className }) {
  return (
    <div className={cn('mx-auto max-w-2xl text-center', className)}>
      <p className="text-xs font-medium tracking-[0.16em] text-accent uppercase">{eyebrow}</p>
      <h2 className="mt-3 text-2xl font-semibold sm:text-3xl">{title}</h2>
      {children && <p className="mt-3 text-ink-muted text-pretty">{children}</p>}
    </div>
  );
}

/** Faux window chrome around a snippet, so code reads as code at a glance. */
function CodeCard({ label, className, children }) {
  return (
    <div
      className={cn(
        'overflow-hidden rounded-[var(--radius-card)] border border-hairline bg-canvas-raised/85',
        'shadow-[0_1px_0_0_rgba(255,255,255,0.04)_inset,0_30px_60px_-40px_rgba(0,0,0,1)]',
        'backdrop-blur-xl',
        className,
      )}
    >
      <div className="flex items-center gap-2 border-b border-hairline px-4 py-3">
        <span aria-hidden className="size-2.5 rounded-full bg-danger/60" />
        <span aria-hidden className="size-2.5 rounded-full bg-warning/60" />
        <span aria-hidden className="size-2.5 rounded-full bg-positive/60" />
        <span className="ml-2 truncate font-mono text-xs text-ink-faint">{label}</span>
      </div>
      <pre className="no-scrollbar overflow-x-auto px-4 py-4 font-mono text-[0.78rem] leading-6 sm:px-5 sm:text-[0.82rem]">
        <code>{children}</code>
      </pre>
    </div>
  );
}

export function HomePage() {
  const { isAuthenticated } = useSession();
  const showAurora = useDecorativeEffects();
  const [menuOpen, setMenuOpen] = useState(false);

  const primaryTo = isAuthenticated ? '/dashboard' : '/signup';
  const primaryLabel = isAuthenticated ? 'Go to dashboard' : 'Create an account';

  return (
    <div className="relative min-h-dvh overflow-hidden">
      {showAurora && (
        <div
          aria-hidden
          className="pointer-events-none absolute inset-x-0 top-0 h-[80vh] opacity-40"
        >
          <Suspense fallback={null}>
            <Aurora colorStops={['#7c5cff', '#22d3ee', '#7c5cff']} amplitude={1} blend={0.55} />
          </Suspense>
        </div>
      )}

      <header className="relative z-20">
        <div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-5 pt-[calc(env(safe-area-inset-top)+1.25rem)] sm:px-6">
          <Link to="/" aria-label="ONEIDP home" className="rounded-lg">
            <Brand />
          </Link>

          <nav className="hidden items-center gap-1 md:flex" aria-label="Site">
            {NAV_LINKS.map((link) => (
              <a
                key={link.href}
                href={link.href}
                className="rounded-lg px-3 py-2 text-sm text-ink-muted transition-colors hover:bg-surface hover:text-ink"
              >
                {link.label}
              </a>
            ))}
            <a
              href={REPO_URL}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm text-ink-muted transition-colors hover:bg-surface hover:text-ink"
            >
              <IconGitHub size={16} />
              GitHub
            </a>
            <span className="mx-2 h-5 w-px bg-hairline" />
            {isAuthenticated ? (
              <Button as={Link} to="/dashboard" size="sm">
                Dashboard
              </Button>
            ) : (
              <>
                <Button as={Link} to="/login" variant="ghost" size="sm">
                  Sign in
                </Button>
                <Button as={Link} to="/signup" size="sm">
                  Get started
                </Button>
              </>
            )}
          </nav>

          <IconButton
            label={menuOpen ? 'Close menu' : 'Open menu'}
            onClick={() => setMenuOpen((open) => !open)}
            aria-expanded={menuOpen}
            className="md:hidden"
          >
            {menuOpen ? <IconClose /> : <IconMenu />}
          </IconButton>
        </div>

        {menuOpen && (
          <div className="mx-5 mt-3 rounded-2xl border border-hairline bg-canvas-raised/95 p-3 backdrop-blur-xl md:hidden">
            <nav className="grid gap-1" aria-label="Site">
              {NAV_LINKS.map((link) => (
                <a
                  key={link.href}
                  href={link.href}
                  onClick={() => setMenuOpen(false)}
                  className="tap-target flex items-center rounded-lg px-3 py-2.5 text-sm text-ink-muted transition-colors hover:bg-surface hover:text-ink"
                >
                  {link.label}
                </a>
              ))}
              <a
                href={REPO_URL}
                target="_blank"
                rel="noreferrer"
                onClick={() => setMenuOpen(false)}
                className="tap-target flex items-center gap-2 rounded-lg px-3 py-2.5 text-sm text-ink-muted transition-colors hover:bg-surface hover:text-ink"
              >
                <IconGitHub size={16} />
                GitHub
              </a>
            </nav>
            <div className="mt-2 grid gap-2 border-t border-hairline pt-3">
              {isAuthenticated ? (
                <Button as={Link} to="/dashboard" fullWidth>
                  Dashboard
                </Button>
              ) : (
                <>
                  <Button as={Link} to="/login" variant="secondary" fullWidth>
                    Sign in
                  </Button>
                  <Button as={Link} to="/signup" fullWidth>
                    Get started
                  </Button>
                </>
              )}
            </div>
          </div>
        )}
      </header>

      <main className="relative z-10">
        {/* Hero */}
        <section className="mx-auto max-w-4xl px-5 pt-16 pb-12 text-center sm:px-6 sm:pt-24 sm:pb-16">
          {/* The animated variants are swapped for static text on phones and
              for reduced-motion users, which also avoids shipping `motion`. */}
          {showAurora ? (
            <Suspense fallback={<Eyebrow />}>
              <AnimatedEyebrow className={EYEBROW_CLASS}>{HERO_EYEBROW}</AnimatedEyebrow>
            </Suspense>
          ) : (
            <Eyebrow />
          )}

          <h1 className="text-[2.25rem] leading-[1.08] font-semibold tracking-tight text-balance sm:text-5xl lg:text-6xl">
            One identity for
            <br className="hidden sm:block" />{' '}
            {showAurora ? (
              <Suspense fallback={<span className="text-ink-muted">every application</span>}>
                <AnimatedHeadline text="every application" className="font-semibold" />
              </Suspense>
            ) : (
              <span className="text-ink-muted">every application</span>
            )}
          </h1>

          <p className="mx-auto mt-5 max-w-xl text-[1.05rem] text-ink-muted text-pretty sm:text-lg">
            ONEIDP is a complete OpenID Connect and OAuth 2.0 provider you run yourself. Register
            your applications, invite your users, and hand out tokens carrying the roles you decide.
            Free, MIT licensed, and one <span className="text-ink">terraform apply</span> away from
            living in your own AWS account.
          </p>

          <div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Button as={Link} to={primaryTo} size="lg" className="w-full sm:w-auto">
              {primaryLabel}
            </Button>
            <Button
              as="a"
              href={REPO_URL}
              target="_blank"
              rel="noreferrer"
              variant="secondary"
              size="lg"
              className="w-full sm:w-auto"
            >
              <IconGitHub size={18} />
              Star on GitHub
            </Button>
          </div>

          <ul className="mt-8 flex flex-wrap items-center justify-center gap-2 text-xs text-ink-muted">
            {HERO_CHIPS.map((chip) => (
              <li
                key={chip}
                className="inline-flex items-center gap-1.5 rounded-full border border-hairline bg-surface px-3 py-1.5"
              >
                <IconCheck size={13} className="text-positive" />
                {chip}
              </li>
            ))}
          </ul>
        </section>

        {/* Features */}
        <section id="features" className="mx-auto max-w-6xl scroll-mt-24 px-5 py-14 sm:px-6 sm:py-20">
          <SectionHeading eyebrow="What you get" title="A provider, not a starter kit">
            Everything a small team needs to stop rolling its own login, and nothing behind an
            enterprise tier.
          </SectionHeading>

          <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((feature) => {
              const Icon = feature.icon;
              return (
                <SpotlightCard
                  key={feature.title}
                  spotlightColor="rgba(124, 92, 255, 0.2)"
                  className="!rounded-[var(--radius-card)] !border-hairline !bg-surface !p-6 backdrop-blur-xl"
                >
                  <span className="grid size-11 place-items-center rounded-xl bg-accent/15 text-accent">
                    <Icon size={22} />
                  </span>
                  <h3 className="mt-4 text-base font-semibold text-ink">{feature.title}</h3>
                  <p className="mt-2 text-sm text-ink-muted text-pretty">{feature.body}</p>
                </SpotlightCard>
              );
            })}
          </div>

          <div className="mt-4 rounded-[var(--radius-card)] border border-hairline bg-surface p-6 backdrop-blur-xl sm:p-8">
            <h3 className="text-base font-semibold text-ink">Boring where it counts</h3>
            <ul className="mt-4 grid gap-3 text-sm text-ink-muted sm:grid-cols-2 lg:grid-cols-3">
              {SECURITY_POINTS.map((point) => (
                <li key={point} className="flex items-start gap-2.5">
                  <IconCheck size={16} className="mt-0.5 shrink-0 text-positive" />
                  <span className="text-pretty">{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        {/* Deployment */}
        <section id="self-host" className="mx-auto max-w-6xl scroll-mt-24 px-5 py-14 sm:px-6 sm:py-20">
          <SectionHeading eyebrow="Your account, your data" title="Deploy it to your own AWS account">
            A Terraform stack ships with the repo. Point it at an empty account, apply, and you have
            a serverless identity provider on a URL you control.
          </SectionHeading>

          <div className="mt-10 grid items-start gap-4 lg:grid-cols-2">
            <CodeCard label="oneidp/terraform">
              {TERMINAL_LINES.map((line, index) => (
                <span key={index} className={TERMINAL_TONE[line.kind]}>
                  {line.kind === 'cmd' && <span className="text-accent">$ </span>}
                  {line.text}
                  {'\n'}
                </span>
              ))}
            </CodeCard>
            <div className="rounded-[var(--radius-card)] border border-hairline bg-surface p-6 backdrop-blur-xl sm:p-8">
              <h3 className="text-base font-semibold text-ink">What Terraform creates</h3>
              <ul className="mt-4 grid gap-3 text-sm text-ink-muted">
                {AWS_STACK.map((item) => (
                  <li key={item} className="flex items-start gap-2.5">
                    <IconCheck size={16} className="mt-0.5 shrink-0 text-cyan" />
                    <span className="text-pretty">{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-5 border-t border-hairline pt-5 text-sm text-ink-muted text-pretty">
                It scales to zero between logins, so a small instance costs cents rather than a
                per-user subscription. Prefer containers? There is a Docker image, a Helm chart and
                plain Kubernetes manifests in the same repo.
              </p>
            </div>
          </div>
        </section>

        {/* Integration */}
        <section className="mx-auto max-w-6xl px-5 py-14 sm:px-6 sm:py-20">
          <SectionHeading eyebrow="Wire it up" title="Standards in, tokens out">
            No SDK to adopt and no proprietary endpoints. If your framework speaks OpenID Connect,
            it already speaks ONEIDP.
          </SectionHeading>

          <div className="mt-10 grid items-start gap-4 lg:grid-cols-2">
            <ol className="grid gap-4">
              {STEPS.map((step, index) => (
                <li
                  key={step.title}
                  className="flex gap-4 rounded-[var(--radius-card)] border border-hairline bg-surface p-5 backdrop-blur-xl sm:p-6"
                >
                  <span
                    aria-hidden
                    className="grid size-9 shrink-0 place-items-center rounded-xl border border-hairline bg-accent/15 font-mono text-sm text-accent"
                  >
                    {index + 1}
                  </span>
                  <div>
                    <h3 className="text-base font-semibold text-ink">{step.title}</h3>
                    <p className="mt-1.5 text-sm text-ink-muted text-pretty">{step.body}</p>
                  </div>
                </li>
              ))}
            </ol>

            <div className="grid gap-4">
              <CodeCard label="GET /.well-known/openid-configuration">
                {'{\n'}
                {DISCOVERY_FIELDS.map(([key, value]) => (
                  <span key={key}>
                    {'  '}
                    <span className="text-accent">{`"${key}"`}</span>
                    {': '}
                    <span className="text-cyan">{value}</span>
                    {',\n'}
                  </span>
                ))}
                <span className="text-ink-faint">{'  ...\n'}</span>
                {'}'}
              </CodeCard>
              <p className="px-1 text-sm text-ink-muted text-pretty">
                Working client examples for Express live in{' '}
                <a
                  href={CLIENT_DEMOS_URL}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 text-ink underline decoration-hairline-strong underline-offset-4 transition-colors hover:decoration-accent"
                >
                  oneidp-client-demo
                  <IconExternal size={14} />
                </a>
                , and the same discovery URL works with any certified library.
              </p>
            </div>
          </div>
        </section>

        {/* Open source */}
        <section
          id="open-source"
          className="mx-auto max-w-6xl scroll-mt-24 px-5 py-14 sm:px-6 sm:py-20"
        >
          <div className="overflow-hidden rounded-[var(--radius-card)] border border-hairline bg-surface backdrop-blur-xl">
            <div className="grid gap-8 p-6 sm:p-10 lg:grid-cols-[1.1fr_1fr] lg:gap-12">
              <div>
                <p className="text-xs font-medium tracking-[0.16em] text-accent uppercase">
                  Open source
                </p>
                <h2 className="mt-3 text-2xl font-semibold sm:text-3xl">
                  MIT licensed, all of it
                </h2>
                <p className="mt-4 text-ink-muted text-pretty">
                  The API, the frontend and the infrastructure code are in one public repository.
                  Read how your passwords are hashed and your tokens are signed instead of taking
                  someone's word for it. Fork it, patch it, run it on your own terms — there is no
                  hosted tier holding the good parts back.
                </p>
                <div className="mt-7 flex flex-col gap-3 sm:flex-row">
                  <Button as="a" href={REPO_URL} target="_blank" rel="noreferrer" size="lg">
                    <IconGitHub size={18} />
                    Browse the source
                  </Button>
                  <Button
                    as="a"
                    href={`${REPO_URL}#deployment-on-kubernetes`}
                    target="_blank"
                    rel="noreferrer"
                    variant="secondary"
                    size="lg"
                  >
                    Read the deploy guide
                  </Button>
                </div>
              </div>

              <dl className="grid gap-4 sm:grid-cols-2 lg:content-start">
                {[
                  ['MIT', 'License, no strings'],
                  ['1 apply', 'From clone to live URL'],
                  ['0', 'Per-user fees, ever'],
                  ['Node + React', 'Express API, Vite SPA'],
                ].map(([value, label]) => (
                  <div
                    key={label}
                    className="rounded-2xl border border-hairline bg-canvas-raised/60 p-5"
                  >
                    <dt className="bg-gradient-to-r from-accent to-cyan bg-clip-text text-xl font-semibold text-transparent">
                      {value}
                    </dt>
                    <dd className="mt-1 text-sm text-ink-muted">{label}</dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        </section>

        {/* Closing CTA */}
        <section className="mx-auto max-w-3xl px-5 pt-6 pb-20 text-center sm:px-6 sm:pb-28">
          <h2 className="text-2xl font-semibold sm:text-3xl">Give it a try</h2>
          <p className="mx-auto mt-4 max-w-xl text-ink-muted text-pretty">
            Create an account on this instance to see the whole thing working end to end, then clone
            the repo and run your own once you are convinced.
          </p>
          <div className="mt-8 flex flex-col items-center justify-center gap-3 sm:flex-row">
            <Button as={Link} to={primaryTo} size="lg" className="w-full sm:w-auto">
              {primaryLabel}
            </Button>
            {!isAuthenticated && (
              <Button
                as={Link}
                to="/login"
                variant="secondary"
                size="lg"
                className="w-full sm:w-auto"
              >
                Sign in
              </Button>
            )}
          </div>
        </section>
      </main>

      <footer className="relative z-10 border-t border-hairline">
        <div className="mx-auto flex max-w-6xl flex-col items-center gap-4 px-5 py-8 pb-[calc(env(safe-area-inset-bottom)+2rem)] sm:flex-row sm:justify-between sm:px-6">
          <Brand size="sm" />
          <nav className="flex items-center gap-5 text-sm text-ink-muted" aria-label="Legal">
            {LEGAL_LINKS.map((link) => (
              <Link key={link.to} to={link.to} className="rounded transition-colors hover:text-ink">
                {link.label}
              </Link>
            ))}
            <a
              href={REPO_URL}
              target="_blank"
              rel="noreferrer"
              className="inline-flex items-center gap-1.5 rounded transition-colors hover:text-ink"
            >
              <IconGitHub size={16} />
              GitHub
            </a>
          </nav>
          <p className="text-xs text-ink-faint">© {new Date().getFullYear()} ONEIDP · MIT</p>
        </div>
      </footer>
    </div>
  );
}
